create schema auditMay16;


/** User tables */

-- ALL
CREATE TABLE auditMay16.ALL_USERS
SELECT * FROM USER_PROFILE_SNAPSHOT
WHERE (ID, TIMESTAMP) IN (SELECT distinct ID, MAX(TIMESTAMP)
	FROM USER_PROFILE_SNAPSHOT
	GROUP BY ID)
;

-- sage users
CREATE TABLE auditMay16.SAGE_USERS (
USER_ID BIGINT(20),
EMAIL VARCHAR(100),
LAST_MONTH TINYINT,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30)
);

truncate table auditMay16.SAGE_USERS;
select * from auditMay16.SAGE_USERS;

LOAD DATA LOCAL INFILE '~/Downloads/sage_users.csv'
INTO TABLE auditMay16.SAGE_USERS
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
;

ALTER TABLE auditMay16.SAGE_USERS
ADD INDEX SAGE_USERS_INDEX_USER_ID (`USER_ID`);

-- test & deamon users
CREATE TABLE auditMay16.DEAMON_USERS AS
SELECT DISTINCT MEMBER_ID 
FROM TEAM_MEMBER_SNAPSHOT
WHERE TEAM_ID = 3329916;

-- use this query if you find a daemon users that are not in the team yet
-- also add the user to the team for future audit
INSERT IGNORE INTO auditMay16.DEAMON_USERS (MEMBER_ID) VALUES (1917752);

CREATE TABLE auditMay16.TEST_USERS AS
SELECT DISTINCT MEMBER_ID 
FROM TEAM_MEMBER_SNAPSHOT
WHERE TEAM_ID = 3329915;

-- use this query if you find a daemon users that are not in the team yet
-- also add the user to the team for future audit
INSERT IGNORE INTO auditMay16.TEST_USERS (MEMBER_ID) VALUES (3338894);

/** NON SAGE USERS **/
CREATE TABLE auditMay16.NON_SAGE_USERS
SELECT * 
FROM auditMay16.ALL_USERS
WHERE ID NOT IN (SELECT USER_ID FROM auditMay16.SAGE_USERS)
AND ID NOT IN (SELECT MEMBER_ID FROM auditMay16.DEAMON_USERS)
AND ID NOT IN (SELECT MEMBER_ID FROM auditMay16.TEST_USERS)
;

ALTER TABLE auditMay16.NON_SAGE_USERS
ADD INDEX NON_SAGE_USERS_INDEX_ID (`ID`);

-- Get all access records during this period
CREATE TABLE auditMay16.AUDIT_ACCESS_RECORDS (
SESSION_ID CHAR(36),
TIMESTAMP BIGINT(20),
USER_ID BIGINT(20),
DATE DATE,
METHOD enum('GET','PUT','POST','DELETE'),
RESPONSE_STATUS INT(11),
ENTITY_ID BIGINT(20),
CLIENT enum('R','PYTHON','WEB','JAVA','COMMAND_LINE','ELB_HEALTHCHECKER','UNKNOWN'),
NORMALIZED_METHOD_SIGNATURE VARCHAR(100),
PRIMARY KEY (SESSION_ID, TIMESTAMP)
);

INSERT IGNORE INTO auditMay16.AUDIT_ACCESS_RECORDS
SELECT AR.SESSION_ID, AR.TIMESTAMP, AR.USER_ID, AR.DATE, AR.METHOD, AR.RESPONSE_STATUS,
PAR.ENTITY_ID, PAR.CLIENT, PAR.NORMALIZED_METHOD_SIGNATURE
FROM ACCESS_RECORD AR, PROCESSED_ACCESS_RECORD PAR
WHERE AR.TIMESTAMP = PAR.TIMESTAMP
AND AR.SESSION_ID = PAR.SESSION_ID
AND AR.TIMESTAMP BETWEEN 1451606400000 AND 1462060800000-1
AND PAR.NORMALIZED_METHOD_SIGNATURE NOT IN ('GET /migration/rowsbyrange',
                                            'GET /migration/rangechecksum',
                                            'GET /migration/count',
                                            'GET /migration/typechecksum',
                                            'GET /migration/status')
;

ALTER TABLE auditMay16.AUDIT_ACCESS_RECORDS
ADD INDEX AUDIT_ACCESS_RECORDS_INDEX_ENTITY_ID (`ENTITY_ID`);

/** ACTIVE USERS **/
CREATE TABLE auditMay16.USER_DATE_RECORD
SELECT USER_ID, MONTH(DATE) AS MONTH, COUNT(DISTINCT DATE) AS DAYS
FROM auditMay16.AUDIT_ACCESS_RECORDS
WHERE USER_ID NOT IN (1, 273950)
AND USER_ID IS NOT NULL
GROUP BY USER_ID, MONTH
HAVING DAYS > 2;

CREATE TABLE auditMay16.ACTIVE_USERS
SELECT DISTINCT USER_ID 
FROM auditMay16.USER_DATE_RECORD 
GROUP BY USER_ID
HAVING COUNT(MONTH) = 4;

/** DOWNLOADS **/
CREATE TABLE auditMay16.DOWNLOAD_RECORDS
SELECT SESSION_ID, USER_ID, ENTITY_ID 
FROM auditMay16.AUDIT_ACCESS_RECORDS
WHERE NORMALIZED_METHOD_SIGNATURE IN ('GET /entity/#/file', 'GET /entity/#/version/#/file')
AND RESPONSE_STATUS IN (200, 307);

/** NODE not in the trash can in 136 **/
CREATE TABLE auditMay16.NOT_TRASH (
ID BIGINT(20) PRIMARY KEY
);

LOAD DATA LOCAL INFILE '~/Downloads/nontrash.csv'
INTO TABLE auditMay16.NOT_TRASH
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;

CREATE TABLE auditMay16.NOT_TRASH_LATEST
SELECT MAX(TIMESTAMP) AS TIMESTAMP, ID 
FROM NODE_SNAPSHOT 
WHERE ID IN (SELECT * FROM auditMay16.NOT_TRASH)
GROUP BY ID;

CREATE TABLE auditMay16.NON_TRASH_NODE_RECORDS
SELECT * 
FROM NODE_SNAPSHOT
WHERE (TIMESTAMP, ID) IN (SELECT * FROM auditMay16.NOT_TRASH_LATEST);

ALTER TABLE auditMay16.NON_TRASH_NODE_RECORDS
ADD INDEX NON_TRASH_NODE_RECORDS_INDEX_ID (`ID`);

ALTER TABLE auditMay16.NON_TRASH_NODE_RECORDS
ADD INDEX NON_TRASH_NODE_RECORDS_INDEX_PROJECT_ID (`PROJECT_ID`);

SELECT * FROM auditMay16.NON_TRASH_NODE_RECORDS;

/** PROJECT SUMMARY **/
CREATE TABLE auditMay16.PROJECT_SUMMARY
SELECT ID, NAME, IS_PUBLIC, IS_CONTROLLED, IS_RESTRICTED, CREATED_BY, CREATED_ON
FROM auditMay16.NON_TRASH_NODE_RECORDS
WHERE NODE_TYPE = 'project';

ALTER TABLE auditMay16.PROJECT_SUMMARY
ADD INDEX PROJECT_SUMMARY_INDEX_ID (`ID`);

UPDATE auditMay16.PROJECT_SUMMARY P
SET P.IS_PUBLIC = ( 
	SELECT MAX(N.IS_PUBLIC)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N
    WHERE N.PROJECT_ID = P.ID)
WHERE P.IS_PUBLIC = FALSE;

UPDATE auditMay16.PROJECT_SUMMARY P
SET P.IS_CONTROLLED = ( 
	SELECT MAX(N.IS_CONTROLLED)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N
    WHERE N.PROJECT_ID = P.ID)
WHERE P.IS_CONTROLLED = FALSE;

UPDATE auditMay16.PROJECT_SUMMARY P
SET P.IS_RESTRICTED = ( 
	SELECT MAX(N.IS_RESTRICTED)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N
    WHERE N.PROJECT_ID = P.ID)
WHERE P.IS_RESTRICTED = FALSE;

ALTER TABLE auditMay16.PROJECT_SUMMARY
ADD COLUMN EMAIL VARCHAR(256);

UPDATE auditMay16.PROJECT_SUMMARY P, auditMay16.ALL_USERS U
SET P.EMAIL = U.EMAIL
WHERE P.CREATED_BY = U.ID;

/** Audit summary **/
-- This table contains the summary of the audit
CREATE TABLE auditMay16.AUDIT_SUMMARY(
VAR_NAME VARCHAR(100),
DESCRIPTION VARCHAR(100),
AUDIT_2016_01_01 BIGINT DEFAULT 0,
AUDIT_2015_08 BIGINT DEFAULT 0,
AUDIT_2015_05 BIGINT DEFAULT 0,
AUDIT_2015_02 BIGINT DEFAULT 0,
AUDIT_2014_11 BIGINT DEFAULT 0
);

LOAD DATA LOCAL INFILE '~/Downloads/audit_input_data.csv'
INTO TABLE auditMay16.AUDIT_SUMMARY
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
;

ALTER TABLE auditMay16.AUDIT_SUMMARY
ADD COLUMN AUDIT_2016_05_01 BIGINT DEFAULT 0;

/** USERS **/

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(*) FROM auditMay16.SAGE_USERS)
WHERE VAR_NAME = "SAGE_USERS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(*) FROM auditMay16.NON_SAGE_USERS)
WHERE VAR_NAME = "NONSAGE_USERS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(*) FROM auditMay16.SAGE_USERS)+(SELECT COUNT(*) FROM auditMay16.NON_SAGE_USERS)
WHERE VAR_NAME = "ALL_USERS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(*) FROM auditMay16.SAGE_USERS)-69 -- LAST AUDIT DATA
WHERE VAR_NAME = "NEW_SAGE";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(*) FROM auditMay16.NON_SAGE_USERS)-14070 -- LAST AUDIT DATA
WHERE VAR_NAME = "NEW_NONSAGE";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT AU.USER_ID) 
	FROM auditMay16.ACTIVE_USERS AU, auditMay16.NON_SAGE_USERS NSU
    WHERE AU.USER_ID = NSU.ID)
WHERE VAR_NAME = "ACTIVE_NONSAGE_USERS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT AU.USER_ID) 
	FROM auditMay16.ACTIVE_USERS AU, auditMay16.SAGE_USERS SU
    WHERE AU.USER_ID = SU.USER_ID)
WHERE VAR_NAME = "ACTIVE_SAGE_USERS";

/** PROJECTS **/

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "project"
	AND IS_PUBLIC = TRUE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_NONSAGE_PUBLIC_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "project"
	AND IS_PUBLIC = TRUE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_SAGE_PUBLIC_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 6 + 2 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "AUDIT_PUBLIC_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "project"
	AND IS_PUBLIC = FALSE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_NONSAGE_PRIVATE_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "project"
	AND IS_PUBLIC = FALSE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_SAGE_PRIVATE_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 366 + 227 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "AUDIT_PRIVATE_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "project"
	AND IS_PUBLIC = TRUE)
WHERE VAR_NAME = "NONSAGE_PUBLIC_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "project"
	AND IS_PUBLIC = TRUE)
WHERE VAR_NAME = "SAGE_PUBLIC_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 597 + 134 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "PUBLIC_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "project"
	AND IS_PUBLIC = FALSE)
WHERE VAR_NAME = "NONSAGE_PRIVATE_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "project"
	AND IS_PUBLIC = FALSE)
WHERE VAR_NAME = "SAGE_PRIVATE_PROJECTS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 3292 + 686 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "PRIVATE_PROJECTS";

/** FILES **/

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "file"
	AND IS_PUBLIC = TRUE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_NONSAGE_PUBLIC_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "file"
	AND IS_PUBLIC = TRUE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_SAGE_PUBLIC_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 1723 + 341 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "AUDIT_PUBLIC_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "file"
	AND IS_PUBLIC = FALSE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_NONSAGE_PRIVATE_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "file"
	AND IS_PUBLIC = FALSE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_SAGE_PRIVATE_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 36225 + 7454 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "AUDIT_PRIVATE_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "file"
	AND IS_PUBLIC = TRUE)
WHERE VAR_NAME = "NONSAGE_PUBLIC_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "file"
	AND IS_PUBLIC = TRUE)
WHERE VAR_NAME = "SAGE_PUBLIC_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 244815 + 11743 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "PUBLIC_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "file"
	AND IS_PUBLIC = FALSE)
WHERE VAR_NAME = "NONSAGE_PRIVATE_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "file"
	AND IS_PUBLIC = FALSE)
WHERE VAR_NAME = "SAGE_PRIVATE_FILES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 558318 + 81525 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "PRIVATE_FILES";

/** TABLES **/

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "table"
	AND IS_PUBLIC = TRUE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_NONSAGE_PUBLIC_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "table"
	AND IS_PUBLIC = TRUE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_SAGE_PUBLIC_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 2 + 1 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "AUDIT_PUBLIC_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "table"
	AND IS_PUBLIC = FALSE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_NONSAGE_PRIVATE_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "table"
	AND IS_PUBLIC = FALSE
	AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_SAGE_PRIVATE_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 335 + 41 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "AUDIT_PRIVATE_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "table"
	AND IS_PUBLIC = TRUE)
WHERE VAR_NAME = "NONSAGE_PUBLIC_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "table"
	AND IS_PUBLIC = TRUE)
WHERE VAR_NAME = "SAGE_PUBLIC_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 41 + 26 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "PUBLIC_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.NON_SAGE_USERS U
	WHERE N.CREATED_BY = U.ID
	AND NODE_TYPE = "table"
	AND IS_PUBLIC = FALSE)
WHERE VAR_NAME = "NONSAGE_PRIVATE_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.SAGE_USERS U
	WHERE N.CREATED_BY = U.USER_ID
	AND NODE_TYPE = "table"
	AND IS_PUBLIC = FALSE)
WHERE VAR_NAME = "SAGE_PRIVATE_TABLES";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = 1337 + 184 -- SUM OF THE 2 NUMBERS ABOVE
WHERE VAR_NAME = "PRIVATE_TABLES";

/** FILE DOWNLOAD **/

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (
	SELECT COUNT(DISTINCT DR.ENTITY_ID)
	FROM auditMay16.DOWNLOAD_RECORDS DR, auditMay16.NON_TRASH_NODE_RECORDS N
	WHERE DR.ENTITY_ID = N.ID 
	AND N.IS_PUBLIC = TRUE)
WHERE VAR_NAME = "AUDIT_PUBLIC_FILE_DOWNLOADS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (
	SELECT COUNT(DISTINCT DR.ENTITY_ID)
	FROM auditMay16.DOWNLOAD_RECORDS DR, auditMay16.NON_TRASH_NODE_RECORDS N
	WHERE DR.ENTITY_ID = N.ID 
	AND N.IS_PUBLIC = TRUE
    AND N.IS_CONTROLLED = TRUE)
WHERE VAR_NAME = "AUDIT_CONTROLLED_PUBLIC_FILE_DOWNLOADS";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (
	SELECT COUNT(DISTINCT DR.ENTITY_ID)
	FROM auditMay16.DOWNLOAD_RECORDS DR, auditMay16.NON_TRASH_NODE_RECORDS N
	WHERE DR.ENTITY_ID = N.ID 
	AND N.IS_PUBLIC = TRUE
    AND N.IS_RESTRICTED = TRUE)
WHERE VAR_NAME = "AUDIT_RESTRICTED_PUBLIC_FILE_DOWNLOADS";

/** FILE UPLOAD **/

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (
	SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.NON_SAGE_USERS NS, auditMay16.NON_TRASH_NODE_RECORDS N
	WHERE N.CREATED_BY = NS.ID
	AND N.IS_PUBLIC = TRUE
    AND N.NODE_TYPE = 'file'
    AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_PUBLIC_FILE_UPLOADS_NONSAGE";

UPDATE auditMay16.AUDIT_SUMMARY
SET AUDIT_2016_05_01 = (
	SELECT COUNT(DISTINCT N.ID)
	FROM auditMay16.SAGE_USERS SU, auditMay16.NON_TRASH_NODE_RECORDS N
	WHERE N.CREATED_BY = SU.USER_ID
	AND N.IS_PUBLIC = TRUE
    AND N.NODE_TYPE = 'file'
    AND CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1)
WHERE VAR_NAME = "AUDIT_PUBLIC_FILE_UPLOADS_SAGE";
    
SELECT VAR_NAME, DESCRIPTION, AUDIT_2016_05_01, AUDIT_2016_01_01, AUDIT_2015_08, AUDIT_2015_05,
AUDIT_2015_02, AUDIT_2014_11
FROM auditMay16.AUDIT_SUMMARY;

/** PROJECT - FILE REPORT **/

-- public_file_uploads_non_sage_current_audit_period.csv
SELECT N.ID AS FILE_ID, N.NAME AS FILE_NAME, N.CREATED_ON AS FILE_CREATED_ON, U.EMAIL AS FILE_CREATED_BY,
P.NAME AS PROJECT_NAME, P.IS_PUBLIC AS IS_PROJECT_PUBLIC, P.IS_CONTROLLED AS IS_PROJECT_CONTROLLED,
P.IS_RESTRICTED AS IS_PROJECT_RESTRICTED, P.EMAIL AS PROJECT_CREATED_BY
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P, auditMay16.NON_SAGE_USERS U
WHERE N.PROJECT_ID = P.ID
AND N.CREATED_BY = U.ID
AND N.NODE_TYPE = 'file'
AND N.CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1
AND N.IS_PUBLIC = TRUE
;

-- public_file_uploads_sage_current_audit_period.csv 
SELECT N.ID AS FILE_ID, N.NAME AS FILE_NAME, N.CREATED_ON AS FILE_CREATED_ON, U.EMAIL AS FILE_CREATED_BY,
P.NAME AS PROJECT_NAME, P.IS_PUBLIC AS IS_PROJECT_PUBLIC, P.IS_CONTROLLED AS IS_PROJECT_CONTROLLED,
P.IS_RESTRICTED AS IS_PROJECT_RESTRICTED, P.EMAIL AS PROJECT_CREATED_BY
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P, auditMay16.SAGE_USERS U
WHERE N.PROJECT_ID = P.ID
AND N.CREATED_BY = U.USER_ID
AND N.NODE_TYPE = 'file'
AND N.CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1
AND N.IS_PUBLIC = TRUE
;

-- public_table_uploads_non_sage_current_audit_period.csv
SELECT N.ID AS TABLE_ID, N.NAME AS TABLE_NAME, N.CREATED_ON AS TABLE_CREATED_ON, U.EMAIL AS TABLE_CREATED_BY,
P.NAME AS PROJECT_NAME, P.IS_PUBLIC AS IS_PROJECT_PUBLIC, P.IS_CONTROLLED AS IS_PROJECT_CONTROLLED,
P.IS_RESTRICTED AS IS_PROJECT_RESTRICTED, P.EMAIL AS PROJECT_CREATED_BY
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P, auditMay16.NON_SAGE_USERS U
WHERE N.PROJECT_ID = P.ID
AND N.CREATED_BY = U.ID
AND N.NODE_TYPE = 'table'
AND N.CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1
AND N.IS_PUBLIC = TRUE
;

-- public_table_uploads_sage_current_audit_period.csv 
SELECT N.ID AS TABLE_ID, N.NAME AS TABLE_NAME, N.CREATED_ON AS TABLE_CREATED_ON, U.EMAIL AS TABLE_CREATED_BY,
P.NAME AS PROJECT_NAME, P.IS_PUBLIC AS IS_PROJECT_PUBLIC, P.IS_CONTROLLED AS IS_PROJECT_CONTROLLED,
P.IS_RESTRICTED AS IS_PROJECT_RESTRICTED, P.EMAIL AS PROJECT_CREATED_BY
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P, auditMay16.SAGE_USERS U
WHERE N.PROJECT_ID = P.ID
AND N.CREATED_BY = U.USER_ID
AND N.NODE_TYPE = 'table'
AND N.CREATED_ON BETWEEN 1451606400000 AND 1462060800000-1
AND N.IS_PUBLIC = TRUE
;

-- public_files_controlled_snapshot_201605.csv
SELECT N.ID AS ID, N.NAME AS FILE_NAME, P.ID AS PROJECT_ID, P.NAME AS PROJECT_NAME
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P
WHERE N.PROJECT_ID = P.ID
AND N.NODE_TYPE = 'file'
AND N.IS_PUBLIC = TRUE
AND N.IS_CONTROLLED = TRUE
AND (N.CREATED_BY IN (SELECT DISTINCT ID FROM auditMay16.NON_SAGE_USERS)
	OR N.CREATED_BY IN (SELECT DISTINCT USER_ID FROM auditMay16.SAGE_USERS))
;

-- public_files_restricted_snapshot_201605.csv
SELECT N.ID AS ID, N.NAME AS FILE_NAME, P.ID AS PROJECT_ID, P.NAME AS PROJECT_NAME
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P
WHERE N.PROJECT_ID = P.ID
AND N.NODE_TYPE = 'file'
AND N.IS_PUBLIC = TRUE
AND N.IS_RESTRICTED = TRUE
AND (N.CREATED_BY IN (SELECT DISTINCT ID FROM auditMay16.NON_SAGE_USERS)
	OR N.CREATED_BY IN (SELECT DISTINCT USER_ID FROM auditMay16.SAGE_USERS))
;

-- public_tables_controlled_snapshot_201605.csv
SELECT N.ID AS ID, N.NAME AS TABLE_NAME, P.ID AS PROJECT_ID, P.NAME AS PROJECT_NAME
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P
WHERE N.PROJECT_ID = P.ID
AND N.NODE_TYPE = 'table'
AND N.IS_PUBLIC = TRUE
AND N.IS_CONTROLLED = TRUE
AND (N.CREATED_BY IN (SELECT DISTINCT ID FROM auditMay16.NON_SAGE_USERS)
	OR N.CREATED_BY IN (SELECT DISTINCT USER_ID FROM auditMay16.SAGE_USERS))
;

-- public_tables_restricted_snapshot_201605.csv
SELECT N.ID AS ID, N.NAME AS TABLE_NAME, P.ID AS PROJECT_ID, P.NAME AS PROJECT_NAME
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P
WHERE N.PROJECT_ID = P.ID
AND N.NODE_TYPE = 'table'
AND N.IS_PUBLIC = TRUE
AND N.IS_RESTRICTED = TRUE
AND (N.CREATED_BY IN (SELECT DISTINCT ID FROM auditMay16.NON_SAGE_USERS)
	OR N.CREATED_BY IN (SELECT DISTINCT USER_ID FROM auditMay16.SAGE_USERS))
;

-- top_public_file_downloads_non_sage_current_audit_period.csv 
SELECT N.ID, N.NAME AS FILE_NAME, COUNT(DISTINCT DR.SESSION_ID) AS SESSION_COUNT,
 N.IS_CONTROLLED AS CONTROLLED, N.IS_RESTRICTED AS RESTRICTED
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.DOWNLOAD_RECORDS DR, auditMay16.NON_SAGE_USERS U
WHERE N.ID = DR.ENTITY_ID
AND N.CREATED_BY = U.ID
AND N.IS_PUBLIC = TRUE
GROUP BY N.ID, N.NAME, N.IS_CONTROLLED, N.IS_RESTRICTED
ORDER BY SESSION_COUNT DESC;

-- top_public_file_downloads_sage_current_audit_period
SELECT N.ID, N.NAME AS FILE_NAME, COUNT(DISTINCT DR.SESSION_ID) AS SESSION_COUNT,
 N.IS_CONTROLLED AS CONTROLLED, N.IS_RESTRICTED AS RESTRICTED
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.DOWNLOAD_RECORDS DR, auditMay16.SAGE_USERS U
WHERE N.ID = DR.ENTITY_ID
AND N.CREATED_BY = U.USER_ID
AND N.IS_PUBLIC = TRUE
GROUP BY N.ID, N.NAME, N.IS_CONTROLLED, N.IS_RESTRICTED
ORDER BY SESSION_COUNT DESC;

-- top_public_file_downloads_current_audit_period
SELECT N.ID, N.NAME AS FILE_NAME, COUNT(DISTINCT DR.SESSION_ID) AS SESSION_COUNT,
 N.IS_CONTROLLED AS CONTROLLED, N.IS_RESTRICTED AS RESTRICTED
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.DOWNLOAD_RECORDS DR
WHERE N.ID = DR.ENTITY_ID
AND N.IS_PUBLIC = TRUE
AND (N.CREATED_BY IN (SELECT DISTINCT ID FROM auditMay16.NON_SAGE_USERS)
	OR N.CREATED_BY IN (SELECT DISTINCT USER_ID FROM auditMay16.SAGE_USERS))
GROUP BY N.ID, N.NAME, N.IS_CONTROLLED, N.IS_RESTRICTED
ORDER BY SESSION_COUNT DESC;

-- top_public_projects_current_audit_period.csv
SELECT P.ID AS PROJECT_ID, P.NAME AS PROJECT_NAME, COUNT(DISTINCT SESSION_ID) AS SESSION_COUNT
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P, auditMay16.AUDIT_ACCESS_RECORDS AR
WHERE AR.ENTITY_ID = N.ID
AND N.PROJECT_ID = P.ID
AND P.IS_PUBLIC = TRUE
AND (N.CREATED_BY IN (SELECT DISTINCT ID FROM auditMay16.NON_SAGE_USERS)
	OR N.CREATED_BY IN (SELECT DISTINCT USER_ID FROM auditMay16.SAGE_USERS))
GROUP BY P.ID, P.NAME
ORDER BY SESSION_COUNT DESC;

-- top_public_projects_sage_current_audit_period.csv
SELECT P.ID AS PROJECT_ID, P.NAME AS PROJECT_NAME, COUNT(DISTINCT SESSION_ID) AS SESSION_COUNT
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P, auditMay16.AUDIT_ACCESS_RECORDS AR,
auditMay16.SAGE_USERS U
WHERE AR.ENTITY_ID = N.ID
AND N.PROJECT_ID = P.ID
AND P.IS_PUBLIC = TRUE
AND N.CREATED_BY = U.USER_ID
GROUP BY P.ID, P.NAME
ORDER BY SESSION_COUNT DESC;

-- top_public_projects_non_sage_current_audit_period.csv
SELECT P.ID AS PROJECT_ID, P.NAME AS PROJECT_NAME, COUNT(DISTINCT SESSION_ID) AS SESSION_COUNT
FROM auditMay16.NON_TRASH_NODE_RECORDS N, auditMay16.PROJECT_SUMMARY P, auditMay16.AUDIT_ACCESS_RECORDS AR,
auditMay16.NON_SAGE_USERS U
WHERE AR.ENTITY_ID = N.ID
AND N.PROJECT_ID = P.ID
AND P.IS_PUBLIC = TRUE
AND N.CREATED_BY = U.ID
GROUP BY P.ID, P.NAME
ORDER BY SESSION_COUNT DESC;

/** USER ACTIVITY REPORTS **/

-- active_daemon_users.csv 
SELECT U.ID, U.EMAIL, CONCAT(U.FIRST_NAME, " ", U.LAST_NAME) AS NAME, U.COMPANY, U.LOCATION,
 SUM(R.DAYS) AS DAYS
FROM auditMay16.ALL_USERS U, auditMay16.USER_DATE_RECORD R, auditMay16.DEAMON_USERS D, auditMay16.ACTIVE_USERS A
WHERE U.ID = R.USER_ID
AND U.ID = D.MEMBER_ID
AND U.ID = A.USER_ID
GROUP BY U.ID, U.EMAIL, NAME, U.COMPANY, U.LOCATION
ORDER BY DAYS DESC;

-- active_non_sage_users.csv
SELECT U.ID, U.EMAIL, CONCAT(U.FIRST_NAME, " ", U.LAST_NAME) AS NAME, U.COMPANY, U.LOCATION,
 SUM(R.DAYS) AS DAYS
FROM auditMay16.NON_SAGE_USERS U, auditMay16.USER_DATE_RECORD R, auditMay16.ACTIVE_USERS A
WHERE U.ID = R.USER_ID
AND U.ID = A.USER_ID
GROUP BY U.ID, U.EMAIL, NAME, U.COMPANY, U.LOCATION
ORDER BY DAYS DESC;

-- active_sage_users.csv
SELECT U.USER_ID, U.EMAIL, CONCAT(U.FIRST_NAME, " ", U.LAST_NAME) AS NAME, SUM(R.DAYS) AS DAYS
FROM auditMay16.SAGE_USERS U, auditMay16.USER_DATE_RECORD R, auditMay16.ACTIVE_USERS A
WHERE U.USER_ID = R.USER_ID
AND U.USER_ID = A.USER_ID
GROUP BY U.USER_ID, U.EMAIL, NAME
ORDER BY DAYS DESC;